### ISSUE TITLE
Modules load, but chromebook panics when starting the virtualbox machine.

### ISSUE THREAD

**Issue by divx118** [divx118/crouton-packages#10]
This could be related to outdated kernel header packages.

**Comment by Watney** [comment]
As a follow-up to my observations detailed at [#1474](https://github.com/dnschneid/crouton/issues/1474)
``uname -r``
``3.10.18``

**Comment by joshrulez2** [comment]
I have replicated this issue on 3.10.18

**Comment by Watney** [comment]
@divx118 the kernel headers in the PPA do appear to be out of date, so I thought I'd try compiling my own. 

I followed the Wiki and downloaded the branch chromeos-3.10. When I ran the script, it complained about not finding intel-pineview. 

(I wasn't sure where to execute the script, and I ended up running ./prepareconfig in ../chromeos/scripts.)

Running make oldconf defaulted to the general config file with a lot of configurable options. 

What might be helpful is if you could please provide a few more details on compiling your own to teach us eager n00bs how to do this ourselves. **Thanks for all of your help!!!**

**Comment by divx118** [comment]
@Watney Hmm `chromeos-intel-pineview` is there see https://chromium.googlesource.com/chromiumos/third_party/kernel/+/chromeos-3.10/chromeos/config/x86_64/

So
```
$ cd ~
$ git clone https://chromium.googlesource.com/chromiumos/third_party/kernel -b chromeos-3.10
```
then
```
$ cd kernel
$ ./chromeos/scripts/prepareconfig chromeos-intel-pineview
$ make oldconfig
```
Maybe you need to disable `CONFIG_ERROR_ON_WARNING` when compiling errors out on a warning, but I am not sure if it is needed anymore. How that is done is explained in the wiki. When then you should do it before setting up the config.  
Any other questions you have I am glad to answer. I am also available on irc channel #crouton. Although I am always online there, I am not always behind my PC. So it can take some time before I answer.

**Comment by Watney** [comment]
Thanks @divx118 I'll give it another try

**Comment by Watney** [comment]
@divx118 just reporting in that I successfully built the 3.10.18 modules, installed them following your guide, and booted a Win7 VirtualBox VM. I'll leave a couple notes for others, should they stumble along. 

1) I disabled ``CONFIG_ERROR_ON_WARNING`` following the [Wiki](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)).

2) My first attempt to compile the kernel failed because of a missing dependency, ``bc``. Running ``sudo apt-get install bc`` enabled a successful run. 

3) Installing ``chromeos-intel-pineview`` presents two configurable options, SCSI and touchscreen drivers to (Y/m/n). I tended to select m (=module), when given the choice. I can't defend this choice, and I'll leave it  wiser and more experienced users to make the *right* choices. 

4) Since I changed the BIOS flags and used @DennisLfromGA 's script to change the kernel, my rc.local file looks like this:

``# umount bindmounts /lib/modules from enter-chroot ``
``for m in `cat /proc/mounts | /usr/bin/cut -d ' ' -f2 | grep /lib/modules| grep -v "^/$" `; do ``
``        umount "$m" ``
``done``
``  ``
``    modprobe vboxdrv ``
``    modprobe vboxpci ``
``    modprobe vboxnetadp ``
``   modprobe vboxnetflt  ``
``  ``
``exit 0``

Lastly, I saved the modules, in case anyone would like to use them. Oh, and thanks again @divx118 for making this possible!! **Kudos**

**Comment by divx118** [comment]
@Watney Thanks for testing this. I a going to update the kernel headers on the ppa.

**Comment by divx118** [comment]
Updated 3.8.11 amd64 and 3.10.18 amd64 the rest will follow. If anyone can check if they work now and don't cause a reboot anymore.  
Following should pull them in:
```
$ sudo apt-get update && sudo apt-get upgrade
```

**Comment by Watney** [comment]
@divx118 reporting in after testing ``intel-pineview`` with
``uname -r``
``3.10.18``
 
I did the following: 
1. Created a fresh chroot with trusty (Ubuntu) 
2. Followed your updated [README](https://github.com/divx118/crouton-packages/blob/master/README.md): downloaded and ran the new ``setup-headers.sh``
3. Installed VirtualBox, which successfully installed the kernel modules using DKMS
4. Fired-up VirtualBox
**success**

@divx118 This is really great! Thank you for your contribution to the community. It took me half a day, even with your guidance, to build the kernel modules myself. As a comparison, I built a fresh chroot, used your PPSA ,and had VirtualBox running in less than 15 minutes! *Thanks so much!*

**Comment by divx118** [comment]
@Watney Thanks for taking the time to test this. If you encounter any problems or want some improvements on the change-kernel-flags script then your welcome to create a new issue for it.

**Comment by Watney** [comment]
I'm glad that I could be of help @divx118. You're up really late ... take care and all the best. Thanks so much!!

**Comment by rrolsbe** [comment]
My c710 with the 847 CPU and kernel version 3.4.0 does NOT reboot when I launch a Virtualbox VM; however, my C710 with 1007 CPU and kernel version 3.8.11 DOES reboot when launching any VM.  Both are running the same version of ChromeOS, Crouton and Virtualbox.  This problem started after the latest automagic ChromeOS update.

I did the following in my 12.04 Crouton chroot but my C710 with the 1007U kernel version 3.8.11: 

sudo apt-get update && sudo apt-get upgrade
ran setup-headers.sh
Logged out of the chroot, shutdown Chromebook and restarted.

Still crashes when launching any VirtualBox VM.   Note the VirtualBox modules did load correctly (verified with the lsmod command).

Thanks for your work on the crouton project!!  I will keep monitoring this thread for any insights/update.

Regards, Ron

**Comment by divx118** [comment]
@rrolsbe You also had this issue https://github.com/divx118/crouton-packages/issues/6 Do you still run the older version of virtualbox that worked on 1007U?
Could you post `$ sudo cat /dev/pstore/console-ramoops` preferably on gist or pastebin and put the link here.

**Comment by rrolsbe** [comment]
Still using older version of Virtualbox on both C710 Chromebooks.

https://gist.github.com/rrolsbe/0db8dad34208d74e3b48#file-console-ramoops-txt

**Comment by rrolsbe** [comment]
Forgot to ask.  Is anyone else still having the crash issue when launching any Virtualbox VM?  See my post three back for details regarding my crash problem.

Much Thanks in Advance
Regards, Ron

**Comment by rrolsbe** [comment]
Loaded latest version of Virtualbox onto C710 with 1007u CPU and all Virtualbox VM's are working properly now.  I had been using an older version of Virtualbox to solve a previous problem I had with with the all VM's not running properly.  Feel free to close this issue.

Regards, Ron

**Comment by divx118** [comment]
@rrolsbe Thanks for reporting back. Glad to see it works for you now :).

**Comment by maxenglander** [comment]
Hi @divx118, I am experiencing this issue. I'm running a recent version of crouton, have `disablevmx` and `lsm.module_locking` disabled (thanks to your awesome scripts), have installed the latest VirtualBox via the PPA on the Virtualbox site.

I should also mention that I am running a custom Chromiumos build with KVM enabled (but am doing `modprobe -r` to remove the KVM extensions before running VirtualBox).

    chroot $ croutonversion
    crouton: version 1-20150511154233~master:392b84e4
    release: trusty
    architecture: amd64
    xmethod: xiwi
    targets: xiwi,touch,keyboard,core
    host: version 7056.0.2015_05_11_2146 (Developer Build - squarkle) developer-build link
    kernel: Linux localhost 3.8.11 #1 SMP Mon May 11 20:26:39 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
    freon: yes

When I start VirtualBox, I says "starting VM", and after half-a-minute or so the host panics and reboots. [Here's](https://gist.github.com/maxenglander/9fc6ce796ff8e53583e5#file-20150512) the contents of `/dev/pstore/console-ramoops`.

Thanks so much for your great tools and your contributions.

**Comment by divx118** [comment]
Just a quick question? Do you have bridged network set? If not try setting it to bridged.
I probably will have some time in the upcoming weekend to take a closer look at it.
