### ISSUE TITLE
Is it possible to install virtualbox on arm-based Chromebooks?

### ISSUE THREAD

**Issue by leto** [divx118/crouton-packages#11]
I have a HP Chromebook 11 and it is not clear to me if it is even possible to run Virtualbox via crouton on this architecture. Can you shed some light or point me in the right direction? Thanks!
```
# uname -a
Linux localhost 3.8.11 #1 SMP Thu Feb 5 21:55:46 PST 2015 armv7l armv7l armv7l GNU/Linux
```

**Comment by divx118** [comment]
Sadly no, there is no virtualbox arm version available.

**Comment by leto** [comment]
Thanks for the quick response! Since I want virtualbox for vagrant, I am going to look into the docker provisioner: http://docs.vagrantup.com/v2/docker/index.html

**Comment by Watney** [comment]
@leto please be sure to post back your Docker experiences. There's a few comments about Docker in [#364](https://github.com/dnschneid/crouton/issues/364)
