### ISSUE TITLE
Headers for 3.14.0

### ISSUE THREAD

**Issue by Watney** [divx118/crouton-packages#13]
@divx118 I feel like the kid who's back asking for more ... 

``uname -a`` 
``Linux localhost 3.14.0 #1 SMP Thu Mar 12 20:35:26 PDT 2015 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux`` 

After you spent all of last weekend updating the repository, there's a new one on the block, 13.4.0 :(

**Comment by divx118** [comment]
No problem I can add those too it is around for a while, but no one asked for it. So I didn't build it. Just curious which device is it ?

**Comment by Watney** [comment]
(*blush*) new Pixel i7

**Comment by divx118** [comment]
divx118 wishes he had a grip on a Pixel i7 :) My HP chromebook 14 with Intel Celeron 2955U will have to do for now. Still have my main notebook with i7 and 12Gb ram which I use for building.

**Comment by Watney** [comment]
@divx118 [update] please *don't* rush the 3.14.0 headers on my account. 

I'm amazed at how well Chrome Remote Desktop runs on a Pixel! It's far superior to a standard Chromebook. The nasty "full screen" notice is rarely troublesome, and it even binds the escape key. All of this is to say that I'm feeling less of a need to run Win7 in VirtualBox. 

Thanks again!!

**Comment by divx118** [comment]
Added 3.14.0 64bit kernel headers to the repo. Let me know if they work. Thanks in advance. https://github.com/divx118/crouton-packages/commit/b4f95046aa61414eb8a776e66a1714d7dbad214f

**Comment by Watney** [comment]
@divx118 thanks for adding the 3.14.0 64bit kernel headers. I successfully installed them in a clean chroot and launched a Win7VM in VirtualBox.

**Comment by divx118** [comment]
Nice, thanks for testing @Watney .
