### ISSUE TITLE
Trying to Build kernel headers and install Virtualbox

### ISSUE THREAD

**Issue by CorySpitzer** [divx118/crouton-packages#20]
I'm trying to get virtual box installed so that I can use Vagrant.

I followed the instructions [here](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)) to the letter, as best as I could.

I got to the part where you log out and log in after running `sudo chmod +x /etc/rc.local`

When I logged out and then back in I got `WARNING: /etc/rc.local failed with code 1`

Here's my `$ croutonversion`:

```
 crouton: version 1-20150730171703~master:f8fdfb0c
 release: trusty
 architecture: amd64
 xmethod: xorg
 targets: xfce,xfce-desktop,keyboard,gtk-extra,extension,core,cli-extra,chrome,audio
 host: version 7077.111.0 (Official Build) stable-channel peppy 
 kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 28 15:00:32 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
 freon: yes
```

Thanks for the help!

**Comment by divx118** [comment]
Sorry I didn't come back to you sooner. Is this still an issue. What output do you get when you run in the chroot `sudo sh -x /etc/rc.local` ?

**Comment by CorySpitzer** [comment]
I never got past this issue, but I haven't been actively working on. 

When I run that command I get

```
+ cat /proc/mounts
+ grep -v ^/$
+ grep /lib/modules
+ /usr/bin/cut -d   -f2
+ uname -r
+ find /lib/modules/3.8.11 -name vboxdrv.ko
+ [ ]
+ exit 0
```

**Comment by divx118** [comment]
It seems you don't have the vboxdrv kernel modules installed. You can follow https://github.com/divx118/crouton-packages/blob/master/README.md to get the kernel headers installed after that you can install virtualbox which will install the modules. If you aren't gonna use virtualbox so no vboxdrv then you need to edit the /etc/rc.local and change it to your own modules you want to load. However you still need to follow the Readme.md to enable loading of external modules and installing the kernel headers.
