### ISSUE TITLE
Accept default option, as indicated.

### ISSUE THREAD

**Issue by JoshMcCullough** [divx118/crouton-packages#21]
After running `sudo sh change-kernel-flags`, I'm prompted to confirm my action and presented with the options 'Y' or 'n'. Since 'Y' is uppercase, indicating the default value, I hit `enter` but then the script simply exited. This is nit-picky, but the 'Y' should be lower case _or_ correctly default when `enter` is pressed.

> Do you want to apply those changes (Y/n)? [enter]
> Exiting with no changes

**Comment by divx118** [comment]
@JoshMcCullough You are totally right, sorry overlooked it. I should  make 'n'  uppercase. I will change it ASAP. Initially I had `y` as default, but decided that it is better to make `n` the default,  so you are sure you want to go ahead.

**Comment by divx118** [comment]
Fixed https://github.com/divx118/crouton-packages/commit/acc9cd74b4e0dfce9730f69557d5d0dba76e239a thanks.

**Comment by JoshMcCullough** [comment]
NP, it's a small bug! Thanks for making this available, I've now got VirtualBox up and running on my Pixel2. :+1:
