### ISSUE TITLE
Comment: Everything works great - Thanx!

### ISSUE THREAD

**Issue by DennisLfromGA** [divx118/crouton-packages#23]
Just wanted to let you know that I finally got around to playing with virtualbox vm's and, after running your `change-kernel-flags.sh` script in Chrome OS and your `setup-headers.sh` script in my 'trusty' chroot, and then installing `VirtualBox 5.0.10` of course, everything is running very smoothly.

I had only used VMware in the past on desktops, etc. and never had tried VirtualBox. I installed a couple of OSes from ISO's and was very surprised just how well they run in a crouton chroot. I then rediscovered 'ova' files and installed some of them - quick and simple. So simple in fact I made a few of my own for safe keeping.

Just thought I'd let you know how it went, I've talked about doing it on a Chromebook but never had.

Thanx for your scripts and your wiki guides and stuff,
-DennisL

*BTW, I did this on my Acer C7 (parrot) with:*
4GB RAM / 20GB STATEFUL / 25GB CHRUBUNTU / 70GB CROUTON

**Comment by divx118** [comment]
np glad I could help you out :) and thanks for the thumbs up.
