### ISSUE TITLE
Change Kernel Flags Script Issue

### ISSUE THREAD

**Issue by kmadill** [divx118/crouton-packages#24]
Hi there,

I've been trying to get Virtualbox to work on my Toshiba Chromebook 2. When I try to run VirtualBox, I get:
-------
Kernel driver not installed (rc=-1908)The VirtualBox Linux kernel driver (vboxdrv) is either not loaded or there is a permission problem with /dev/vboxdrv. Please reinstall the kernel module by executing  '/etc/init.d/vboxdrv setup'as root. If it is available in your distribution, you should install the DKMS package first. This package keeps track of Linux kernel changes and recompiles the vboxdrv kernel module if necessary.

where: suplibOsInit
what:  3
VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT.
---------

When I attempt to run '/etc/init.d/vboxdrv setup', I get command not found. 

I found your page, but the change-kernel-flags fails for me. I get:
--------
(trusty)root@localhost:~# sudo sh change-kernel-flags 
change-kernel-flags: 1: change-kernel-flags: rootdev: not found
change-kernel-flags: 1: change-kernel-flags: cgpt: not found
/tmp/change-kernel-flags.AfA.
change-kernel-flags: 246: change-kernel-flags: /usr/share/vboot/bin/make_dev_ssd.sh: not found
make_dev_ssd.sh --save_config Failed
---------

Any idea why it's failing?

Many thanks!

**Comment by kmadill** [comment]
Of course, right after posting this I realised my mistake. I had to run this script from the crosh shell! You'd think your bolding of that work in the readme would have clued me in sooner...!

**Comment by divx118** [comment]
np :)
