### ISSUE TITLE
Something broke VirtualBox today

### ISSUE THREAD

**Issue by Watney** [divx118/crouton-packages#25]
Hello, 

After CrOS updated to Version 48.0.2564.23 beta (64-bit), I followed my standard procedure: 

1. Change the kernel flags 
2. Reboot 
3. Update crouton (which also updates all packages) 
4. Reboot 
5. Start my trusty chroot and then VirtualBox: boom! 

```Kernel driver not installed (rc=-1908) The VirtualBox Linux kernel driver (vboxdrv) is either not loaded or there is a permission problem ...```

But, ```lsmod``` confirms the kernel modules are loading: 
```vboxnetflt             28093  0``` 
```vboxnetadp             25540  0``` 
```vboxpci                          23143  0``` 
```vboxdrv               361092  3 vboxnetadp,vboxnetflt,vboxpci```

So, I purged VirtualBox, reinstalled the headers from the PPA, and reinstalled VirtualBox. After confirming the kernel modules are indeed loading, tried again: same error. 

I would keep troubeshooting, but I'm stuck. Any suggestions would be most welcome. Thanks!

[Edit] A little more information. The output of 
```$sudo /etc/init.d/vboxdrv setup``` 
```Stopping VirtualBox kernel modules ...done.``` 
```Uninstalling old VirtualBox DKMS kernel modules ...done.``` 
```Trying to register the VirtualBox kernel modules using DKMS ...done.```
```Starting VirtualBox kernel modules ...failed!```
```     (Cannot locate the VirtualBox device)```

**Comment by divx118** [comment]
Hmm it seems not to be able to create the device node. I need to try it myself soon. Currently I have no virtualbox installed on my chromebook.

 > or there is a permission problem

I wonder what the chromeos developers changed this time...

**Comment by Watney** [comment]
I'll check the output later today and report. 

Please don't rush to install yourself. I'm going to blow crouton away. It's unusable now: the video tares badly and you cannot switch between CrOS and the chroot. And to be honest, I'm not using it :) 

Thanks for the reply. I'll post the output later

**Comment by Watney** [comment]
According to [the current Oracle user manual](http://download.virtualbox.org/virtualbox/5.0.10/UserManual.pdf), ```vbox``` is installed in ```/etc```

The ouput of ```$ ls -al /dev |grep vbox``` is null, but 

```$ ls -al /etc |grep vbox```
```drwxr-xr-x   2 root root    4096 Nov 10 09:54 vbox```

VirtualBox 5.0 introduced several changes, one of which is the error message over when the chroot is launched. I'll report that message momentarily, but I'm first posting this comment because switching to CrOS in Crouton will crash the display.

**Comment by neurocyte** [comment]
I also use virtualbox on crouton and it broke for me too. /dev/vboxdrv does not exist even though lsmod shows that all the vbox modules are loaded. /proc/devices and /proc/misc don't show anything vbox related. dmesg is quiet too.

**Comment by neurocyte** [comment]
Sorry, that was not accurate. dmesg *does* show the regular "Chromium OS LSM: init_module locking-ignored" message for vboxdrv, but nothing else.

**Comment by divx118** [comment]
@neurocyte Yep thanks, that is what I expected. I wonder if we can make the device node manually after  the modules are loaded ....
@Watney Thanks anyway for reporting the issue. :)

**Comment by divx118** [comment]
Damn I don't seem to be affected.
```
(trusty)m@localhost:~$ ls -al /dev|grep vbox
crw-------  1 root root       10,  56 Dec 10 18:43 vboxdrv
crw-------  1 root root       10,  55 Dec 10 18:43 vboxdrvu
crw-------  1 root root       10,  54 Dec 10 18:43 vboxnetctl
drwxr-x---  3 root vboxusers       60 Dec 10 18:42 vboxusb
```
Version 48.0.2564.23 dev (64-bit)
Platform 7647.18.0 (Official Build) dev-channel falco
Firmware Google_Falco.4389.92.0

**Comment by divx118** [comment]
Can anyone post there kernel version `uname -a`? I think it has to be kernel related I am on 3.8.11.

**Comment by Watney** [comment]
Before I blew my system away, I checked and it was 3.14.0 (2015 Pixel)

**Comment by divx118** [comment]
Ok, thanks I am going to build some new kernel header files for 3.14 and
see if that will fix it.

**Comment by divx118** [comment]
Sorry it took so long, however I [updated the header files for 3.14](https://github.com/divx118/crouton-packages/commit/2958682dcd5df30ae7195d30b1cdb33e9db6d2b1) see if that solves the issue.  
Use the following in a chroot to update the headers.
```
$ sudo apt-get update && sudo apt-get upgrade
```
Then rebuild the virtuabox modules.

If there are still issues, then please reply and I will reopen this.
