### ISSUE TITLE
rootdev: not found, cgpt: not found

### ISSUE THREAD

**Issue by mustacken** [divx118/crouton-packages#30]
Hello. Thank you for creating this repo and script! However, while following the instructions on a fresh crouton install of precise, I get the following from running the script:

    sudo sh change-kernel-flags
    change-kernel-flags: 1: /home/mustacken/Downloads/change-kernel-flags: rootdev: not found
    change-kernel-flags: 1: /home/mustacken/Downloads/change-kernel-flags: cgpt: not found
    /tmp/change-kernel-flags.tvU.
    change-kernel-flags: 246: /home/mustacken/Downloads/change-kernel-flags: /usr/share/vboot/bin/make_dev_ssd.sh: not found
    make_dev_ssd.sh --save_config Failed

Kernel version:

    uname -a
    Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:11:59 PST 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm using a Lenovo N21 80MG with precise installed on an SD card. I've searched google for rootdev and cgpt and can't seem to find anyone else with the same issue.

Thanks,

**Comment by divx118** [comment]
@mustacken The change-kernel-flags script needs to be run in a crosh shell, not in a chroot. The setup-headers.sh needs to be run in a chroot.

**Comment by divx118** [comment]
I assume this can be closed now. If the above didn't work then please reply here and I will reopen.
