### ISSUE TITLE
Virtualbox will not start after ChromeOS update / error running the hange-kernel-flags script

### ISSUE THREAD

**Issue by robertstrom** [divx118/crouton-packages#31]
Hello,

My ChromeOS was updated to  47.0.2526.110 (64-bit) a few days ago and I went to run Virtualbox in my Trusty XFCE crouton and the VM would not start.

At that point I went into the crosh, entered a shell and issued the command 

sudo sh ~/Downloads/change-kernel-flags -r

When I issue this command I get this error

chronos@localhost ~ $ sudo sh ~/Downloads/change-kernel-flags -r
List of backup kernel files in "/mnt/stateful_partition/backups"

**No backup kernels found in /mnt/stateful_partition/backups**

I checked the /mnt/stateful_partition/backups directory I found that there was a backup file in it **kernel_A_20151220_163251.bin**

Then I tried moving the backup file out of the directory and reran the command. Still the same error.

NOTE: my crouton is on an external SSD drive. I have not remapped the crouton directory. I start the crouton using this command

**sudo enter-chroot -c /media/removable/Chroots/chroots -n xfce startxfce4**

Hopefully someone can help me to get my kernel flags updated so that I can run my Virtualbox VM's again.

TIA,

Robert

**Comment by divx118** [comment]
@robertstrom Just run `sudo sh ~/Downloads/change-kernel-flags` without -r to change the flags again. -r is needed when you want to  restore an old kernel or undo the flag changes. Normally you won't want this.

I will look a the script and see why it can't find your backup kernel, because that should work also.

**Comment by robertstrom** [comment]
@divx118  - Thanks ... that worked great! Appreciate the response.!

**Comment by divx118** [comment]
@robertstrom Thanks for the feedback that it worked.
