### ISSUE TITLE
no make_dev_ssd.sh script on chromebook pixel

### ISSUE THREAD

**Issue by ximsce** [divx118/crouton-packages#44]
Hi,
Trying to run change-kernel-flags on a chromebook pixel (kernel 3.14, xenial chroot) results in:

/usr/share/vboot/bin/make_dev_ssd.sh: not found
make_dev_ssd.sh --save_config Failed

am I missing a vboot package?  I installed vboot-kernel-utils and vboot-utils, but those didn't help.

Thanks!

**Comment by divx118** [comment]
You should run it in a crosh shell and not inside the chroot.

**Comment by ximsce** [comment]
Oh, the set of instructions I was following said all the commands were in the chroot.  Obviously, that didn't apply to this part...  It would be cool if there were a way to denote in shell commands which type you are supposed to be in.

Thank you for pointing me in the right direction!

**Comment by divx118** [comment]
Well it is mentioned in the readme ;) There should be however a way to detect in which shell you are in. As soon as I have some time I will update the script to spit out a warning to point in the right direction.
