### ISSUE TITLE
ChromeOS vm

### ISSUE THREAD

**Issue by DennisLfromGA** [divx118/crouton-packages#5]
Granted I know next to nothing about running vm's on a Chromebook but 'crouton-packages' seems like a pretty slick way to accomplish it via a chroot.

I'm thinking about trying this out on my HP Chromebook 14 but I think I need a little guidance/explanation before I dive in. I've seen wiki pages on the crouton site that discuss this but I'm still a little confused after reading them.

Question: Do I need to follow and perform the steps in all 3 articles below?
 1. '[Build kernel headers and install Virtualbox (x86)](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86))'
 2. '[Build chrome os kernel and kernel modules](https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules)'
 3. (a)  '[Repack kernel to Enable VT_x for Virtualbox](https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox)'
 3. (b) '[Can't disable module_locking in ChromeOS dev channel #1278](https://github.com/dnschneid/crouton/issues/1278)'

Also, an article on the chromium site talks about *'Running virtual machines on your chromebook'* and under '[Enabling VMX Support](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook#TOC-Enabling-VMX-Support)' it seems to indicate that you have to do a 'hard-disconnect' of the battery before it's effective.(???) They also provide a couple of compressed tar files, one a 'qroot' with libraries and stuff and another with a an image. So, I guess with these additions, one can run a vm in ChromeOS without the need of a modded chroot.(???)

I'd appreciate any insight you can give me along these lines.
I realize I've asked a lot and you probably don't have the time or, like me, patience to walk me  through this so I'll understand if this goes unanswered. :)

Confused,
-DennisL

**Comment by divx118** [comment]
You just can use this [repo](https://github.com/divx118/crouton-packages/blob/master/README.md), so you don't need to build the kernel headers yourself. So skipping 1 and 2  in your list. BTW guide 2 is about building modules for the chromeos kernel still need to migrate the 2 pages into one, but that can wait until we are sure what will happen with 4 (b).  
3 (a) Is not really needed, It just improves speed in the VM. If you don't enable VT-x be sure to disable that setting in virtualbox for your machine. By default that setting is on.
4 (b) Not a problem yet, if you are not using dev channel. On beta and stable it still works.

They are using [qemu](http://wiki.qemu.org/KVM) for their virtual machines that is what the files are about. You can just as well use virtualbox, it is "easier" to setup and works very well. Disconnecting the battery or paperclip in the pinhole or on the newer ones there seems to be a bios switch, is all to make it persistent. So you don't need that. Certainly not needed to try things out.

**Comment by DennisLfromGA** [comment]
***Thanx a lot for the answers and explanations.*** 
I've just got a 16GB SSD in this thing right now but I'm going to get a 128GB SSD soon'ish - the SSD replacement on this thing looks like a booger :)
