### ISSUE TITLE
C710 using 847 Crouton/Virtualbox works but on with 1007u does not. 

### ISSUE THREAD

**Issue by rrolsbe** [divx118/crouton-packages#6]
Just created a long post regarding this issue and the Firefox browser crashed.  So I will start this thread short and sweet on this attempt.  Both 32bit and 64bit Virtualbox guest OS VM's stop responding when using the C710 with the 1007u processor.  Both C710 are using the save version of Crouton/Virtualbox.  Anyone have a similar problem?

Any advice would be greatly Appreciated!!
Regards, Ron

**Comment by divx118** [comment]
It can be that you are no longer able to disable module_locking through the sysfs path. See https://github.com/dnschneid/crouton/issues/1278 A workaround is to remove the sysfs lines in rc.local and follow https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox This will disable verified kernel boot, so you will be a bit less secure.  
Before you do anything first do a `ls -al /sys/module/lsm/parameters` to see if you indeed miss this directory and are suffering from the issue I mentioned above.

**Comment by rrolsbe** [comment]
divx118

Thanks for the reply!  The directory does exist.  All of the vbox modules are loading and are the same as lsmod on working machine.  Guests do launch but most times lockup before even reaching the guest desktop, then I get a message that Virtualbox is not responding and would I like to continue or terminate (the hosting OS Crouton  does NOT lock up.  Maybe someone on this thread will indicate whether they are able to launch Virtualbox guests using their Chromebook/Crouton installation.  If I know someone got it working smoothly using the 1007u and the 3.8.11 kernel, then I have something to shoot for.

Thanks Very Much Again
Regards, Ron

**Comment by rrolsbe** [comment]
Appears to be a problem with the latest version of Virtualbox.  I reverted to the same (previous) version of Virtualbox I am using on the C710 with the 847 CPU.  Version 4.3.20 r96996 appears to work on the C710 with 1007u.

Regards, Ron
