### ISSUE TITLE
change-kernel-flags reports the following errors 

### ISSUE THREAD

**Issue by MatthiasLiszt** [divx118/crouton-packages#66]
sudo sh ~/Downloads/change-kernel-flags
[sudo] password for mahagugu: 
/home/mahagugu/Downloads/change-kernel-flags: 1: /home/mahagugu/Downloads/change-kernel-flags: rootdev: not found
/home/mahagugu/Downloads/change-kernel-flags: 1: /home/mahagugu/Downloads/change-kernel-flags: cgpt: not found
/tmp/change-kernel-flags.sgq.
/home/mahagugu/Downloads/change-kernel-flags: 246: /home/mahagugu/Downloads/change-kernel-flags: /usr/share/vboot/bin/make_dev_ssd.sh: not found
make_dev_ssd.sh --save_config Failed

**Comment by divx118** [comment]
@MatthiasLiszt Did you execute it in the crosh shell? The script is not meant to be executed inside a chroot.

**Comment by MatthiasLiszt** [comment]
Sorry , but I exactly did that. I run it again just now and it told me the following.
(suppose that is what it should do )

/tmp/change-kernel-flags.sXK.2
Saving Kernel A config to /tmp/change-kernel-flags.sXK.2
(Kernels have not been resigned.)
"lsm.module_locking=0"  is already added to the kernel cmdline.
"disablevmx=off"        is already added to the kernel cmdline.

"lsm.module_locking=0 disablevmx=off" are already added to the kernel cmdline.
If you wish to revert the original kernel, run "change-kernel-flags -r"
which will give you the option to copy back the original kernel
from an earlier created backup.

**Comment by divx118** [comment]
@MatthiasLiszt Yes, that is correct. You should be able to insmod external modules now. Closing this issue as it seems resolved. The error message above in your first post is from running it inside a chroot, because looking at the path `/home/mahagugu/Downloads` and not what it should have been `/home/chronos/user/Downloads`.
