### ISSUE TITLE
Your kernel version 3.18.0-14593-g9c23f3f1b8d6 with architecture amd64 is not supported 

### ISSUE THREAD

**Issue by natethegreatsu** [divx118/crouton-packages#67]
Hey im trying to run
$  sudo sh setup-headers.sh
when i do iget
sudo sh setup-headers.sh
[sudo] password for blackice: 
# This script will add the repo to your sources, download
and install the kernel headers appropriate to your
kernel version and architecture.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.2.20).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2017-07-19 18:45:03--  https://raw.githubusercontent.com/divx118/crouton-packages/master/mauricevankruchten@gmail.com.gpg.key
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1756 (1.7K) [text/plain]
Saving to: 'STDOUT'

-                   100%[===================>]   1.71K  --.-KB/s    in 0s      

2017-07-19 18:45:03 (211 MB/s) - written to stdout [1756/1756]

OK
--2017-07-19 18:45:04--  https://raw.githubusercontent.com/divx118/crouton-packages/master/conf/distributions
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 671 [text/plain]
Saving to: './tmp_dist'

./tmp_dist          100%[===================>]     671  --.-KB/s    in 0s      

2017-07-19 18:45:04 (97.3 MB/s) - './tmp_dist' saved [671/671]

3.18.0-14593-g9c23f3f1b8d6
amd64
Your kernel version 3.18.0-14593-g9c23f3f1b8d6 with architecture amd64 is not supported
(xenial)blackice@localhost:~$ 

Please help

**Comment by divx118** [comment]
duplicate https://github.com/divx118/crouton-packages/issues/45

**Comment by natethegreatsu** [comment]
Thank you I will try gallium

**Comment by divx118** [comment]
@natethegreatsu Yeah, best option. Galiumos is in principle xubuntu, but with some kernel patches specific to chromeos hardware. It works very nice.
