### ISSUE TITLE
Kernel not supported.

### ISSUE THREAD

**Issue by ghost** [divx118/crouton-packages#70]
Kernel 3.18.1 kernel with amd64 arch doesn't install.

**Comment by divx118** [comment]
@idSoftwareWolf 

> Virtual box modules and the repo is currently broken https://github.com/divx118/crouton-packages/issues/45 the change-kernel-flags script to disable "module_locking" mentioned above still works

See https://github.com/divx118/crouton-packages/blob/master/README.md
