### ISSUE TITLE
apt-get update fails + rc.local code 1 + cannot access module locking

### ISSUE THREAD

**Issue by Watney** [divx118/crouton-packages#8]
@divx118 Firstly, thank you for all of your work on crouton. After carefully reading your contribution to the Wiki on creating headers for Virtualbox, I stood from my chair and applauded! Genius. 

I'm trying to use the kernel headers from your PPA. I have not attempted to compile my own. However, I've run into three questions. Perhaps you can offer suggestions, please. 

1. **apt-get update error.** I ran the script ``setup-headers.sh`` and now, with every ``apt-get update`` I get the following error message: 
``W: Failed to fetch https://raw.github.com/divx118/crouton-packages/master/dists/3.10.18/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)``

2. **rc.local failed with code 1** After completing the installation, including Virtualbox (from the Virtualbox.org ppa), I get the following error when lauching 
``sudo startxfce4 -n vbox`` 
``Entering /mnt/stateful_partition/crouton/chroots/vbox...`` 
``WARNING: /etc/rc.local failed with code 1`` 

3. **troubleshoot Virtualbox** Virtualbox fails to launch reporting: Kernel driver not installed (rc=-1908) 
I've checked the following: 
a. ``sudo /etc/init.d/vboxdrv setup``
``Stopping VirtualBox kernel modules ...done.``
``Uninstalling old VirtualBox DKMS kernel modules ...done.``
``Trying to register the VirtualBox kernel modules using DKMS ...done.``
``Starting VirtualBox kernel modules ...failed!``
b. The kernel headers and sym links are installed. 
``ls -al /lib/modules/3.10.18``
``build -> /usr/src/linux-headers-3.10.18``
and, there is a directory `` /usr/src/linux-headers-3.10.18``
c. rc.local is correct and executable 
d. However, when I  run
``sudo /etc/rc.local`` it reports
``chmod: cannot access '/sys/module/lsm/parameters/module_locking': No such file or directory``

Thanks for all of your help!!

[EDIT] @divx118 I found your comment on [#1278](https://github.com/dnschneid/crouton/issues/1278#issuecomment-68185407) 
>I am working on a script to simplify changing kernel flags with also the possibility to revert any changes, so go back to a previously backed up signed kernel. Once this is done I will update the wiki pages.  

My issue may be related to your comment and the thread discussion. If so, please forgive me. I'll patiently wait ... *Thanks again!!*

**Comment by divx118** [comment]
1) I still need to add x86 modules to the repo for 3.10.18 kernel. Although we don't use them apt-get will complain they aren't there. 
Since you installed the headers, just remove `/etc/apt/sources.list.d/crouton-packages.list` and the message will go away.
2 and 3) Yes you are correct. My script is almost ready, but time is a bit of an issue right now. However I added the steps to change the kernel flags to the crouton wiki. See https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox  
It is pretty easy and straight forward. BTW you need to follow those steps every time after a chromeos update.

**Comment by Watney** [comment]
Thanks so much!! I'll give it a go. Would you like me to close the issue, or leave it open? Thanks again and please don't feel any pressure from me. Like I said at the outset, that someone finally showed us how to compile a kernel for virtualbox is totally amazing! I asked about this back in the days of the Cr48s, but gave up. Genius!!
